language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  # Must install via code.google.com for go <= 1.3, golang.org for go >= 1.4. 
  - go get golang.org/x/tools/cmd/cover || true
  - go get code.google.com/p/go.tools/cmd/cover || true

script:
  - $HOME/gopath/bin/goveralls -repotoken SUtdBlJVLZGVFk5XeIt6I7Rdi1OUTRMTN
